/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OtherRouteImport } from './routes/other'
import { Route as ThirdRouteImport } from './routes/third'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const ThirdRoute = ThirdRouteImport.update({
  id: '/third',
  path: '/third',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/other': typeof OtherRoute
  '/third': typeof ThirdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/other': typeof OtherRoute
  '/third': typeof ThirdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/other': typeof OtherRoute
  '/third': typeof ThirdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/other' | '/third'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/other' | '/third'
  id: '__root__' | '/' | '/other' | '/third'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OtherRoute: typeof OtherRoute
  ThirdRoute: typeof ThirdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third': {
      id: '/third'
      path: '/third'
      fullPath: '/third'
      preLoaderRoute: typeof ThirdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OtherRoute: OtherRoute,
  ThirdRoute: ThirdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
